name: smartroots
description: ""
publish_to: 'none'
version: 1.0.2+22

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: any
  maplibre_gl: ^0.24.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_polyline_points: ^3.1.0
  maps_toolkit: ^3.1.0
  flutter_tts: ^4.2.3
  matomo_tracker: ^6.1.0
  wakelock_plus: ^1.3.3
  map_launcher: ^4.4.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  build_runner: ^2.9.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/parkstark_foreground.png
    - assets/p_reserviert.png
    - assets/base_map_light_thumbnail.png
    - assets/base_map_dark_thumbnail.png
    - assets/base_map_satellite_thumbnail.png
    - assets/smart_logo.png
    - assets/general/marker_user_position_general.png
    - assets/general/marker_walking_general.png
    - assets/general/marker_bus_general.png
    - assets/general/marker_train_general.png
    - assets/general/marker_place_general.png
    - assets/general/line_walking_general.png
    - assets/general/marker_parking_avbl_yes_general.png
    - assets/general/marker_parking_avbl_no_general.png
    - assets/general/marker_parking_avbl_unknown_general.png
    - assets/general/marker_mini_parking_yes_general.png
    - assets/general/marker_mini_parking_no_general.png
    - assets/general/marker_mini_parking_unknown_general.png
    - assets/vision_impaired/marker_user_position_vision_impaired.png
    - assets/vision_impaired/marker_walking_vision_impaired.png
    - assets/vision_impaired/marker_bus_vision_impaired.png
    - assets/vision_impaired/marker_train_vision_impaired.png
    - assets/vision_impaired/marker_place_vision_impaired.png
    - assets/vision_impaired/line_walking_vision_impaired.png
