networks:
  proxy:
    name: navi4all-proxy

services:
  core-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: core-backend
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      proxy:
    ports:
      - "8010:8010"

  core-redis:
    image: redis:latest
    container_name: core-redis
    networks:
      proxy:
